name: Release - Maven

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release Version
        required: true
        default: 3.1.1
      snapshot-version:
        description: Snapshot Version
        required: true
        default: 3.1.2-SNAPSHOT

run-name: 'version set to ${{ inputs.release-version }} for release'

jobs:
  main:
    uses: codbex/codbex-infra/.github/workflows/platform-release.yaml@main
    with:
      platform-name: olingo-odata2
      release-version: ${{ inputs.release-version }}
      snapshot-version: ${{ inputs.snapshot-version }}
      # maven-release: true
      buildx-enabled: false
      release-content: |
        ## olingo-odata2 - ${{ inputs.release-version }}
    secrets: inherit
